config/routes.rb
require 'sidekiq/web'

Rails.application.routes.draw do
  authenticate :user, lambda { |u| u.admin? } do
    mount Sidekiq::Web => '/sidekiq'
  end

  use_doorkeeper
  devise_for :users, controllers: { omniauth_callbacks: 'oauth_callbacks' }
  root to: 'questions#index'

  get '/user/get_email', to: 'users#new'
  post '/user/set_email', to: 'users#create'

  namespace :api do
    namespace :v1 do
      resources :profiles, only: [:index] do
        get :me, on: :collection
      end

      resources :questions, except: %i[new edit] do
        resources :answers, except: %i[new edit], shallow: true
      end
    end
  end

  concern :voted do
    member do
      patch :vote_up
      patch :vote_down
      delete :vote_cancel
    end
  end

  concern :commentable do
    resources :comments, only: :create, shallow: true
  end

  resources :files, only: [:destroy]
  resources :questions, concerns: %i[voted commentable] do
    resources :answers, concerns: %i[voted commentable], shallow: true do
      patch :mark_as_best, on: :member
    end
    resources :subscriptions, only: %i[create destroy], shallow: true
  end

  resources :rewards, only: :index
  resources :searches, only: :index

  mount ActionCable.server => '/cable'
end

app/models/question.rb
class Question < ApplicationRecord
  include Linkable
  include Votable
  include Commentable

  has_many :answers, dependent: :destroy
  has_many :subscriptions, dependent: :destroy
  belongs_to :user
  belongs_to :best_answer, class_name: 'Answer', optional: true
  has_one :reward, dependent: :destroy

  has_many_attached :files

  accepts_nested_attributes_for :reward, reject_if: :all_blank

  default_scope -> { order(created_at: :desc) }

  validates :title, :body, presence: true

  after_create :subscribe_to_author!

  def mark_as_best(answer)
    transaction do
      update!(best_answer: answer)
      reward.update!(user: answer.user)
    end
  end

  def other_answers
    answers.where.not(id: best_answer)
  end

  private

  def subscribe_to_author!
    subscriptions.create!(user: user)
  end
end

app/controllers/api/v1/questions_controller.rb
class Api::V1::QuestionsController < Api::V1::BaseController
  skip_authorization_check

  before_action :find_question, only: %i[show update destroy]

  def index
    @questions = Question.includes(:answers)
    render json: @questions
  end

  def show
    render json: @question, serializer: QuestionSeparateSerializer
  end

  def create
    @question = current_resource_owner.questions.new(question_params)

    if @question.save
      render json: @question, status: :created
    else
      render json: { errors: @question.errors }, status: :unprocessable_entity
    end
  end

  def update
    authorize! :update, @question

    if @question.update(question_params)
      render json: @question, status: :created
    else
      render json: { errors: @question.errors }, status: :unprocessable_entity
    end
  end

  def destroy
    authorize! :destroy, @question

    @question.destroy
    render json: { messages: ['Question was successfully deleted.'] }
  end

  private

  def find_question
    @question = Question.find(params[:id])
  end

  def question_params
    params.require(:question).permit(:title, :body)
  end
end

app/controllers/questions_controller.rb
class QuestionsController < ApplicationController
  include Voted

  before_action :authenticate_user!, except: %i[index show]
  before_action :find_question, only: %i[show edit update destroy]
  before_action :load_subscription, only: %i[show update]
  after_action :publish_question, only: %i[create]

  authorize_resource

  def index
    @questions = Question.all
  end

  def show
    @best_answer = @question.best_answer
    @other_answers = @question.answers.where.not(id: @question.best_answer_id)
    @answer = Answer.new
    @answer.links.new
    set_gon
    @comment = Comment.new
  end

  def new
    @question = Question.new
    @question.links.new # .build
    @question.build_reward
  end

  def edit
    @question = Question.find(params[:id]) if current_user.author_of?(@question)
  end

  def create
    @question = current_user.questions.new(question_params)

    if @question.save
      flash[:notice] = 'Your question successfully created.'
      redirect_to @question
    else
      render :new
    end
  end

  def update
    if current_user.author_of?(@question)
      if @question.update(question_params)
        flash[:notice] = 'Your answer is updated'
        redirect_to @question
      else
        flash[:error] = 'Question is not updated'
        render :edit
      end
    else
      flash[:error] = 'You are not author of this question'
      redirect_to questions_path
    end
  end

  def destroy
    if current_user.author_of?(@question)
      @question.destroy
      flash[:notice] = 'Your question successfully deleted!'
      redirect_to questions_path
    else
      flash[:error] = 'You are not author of this question'
      redirect_to questions_path
    end
  end

  private

  def load_subscription
    @subscription = @question.subscriptions.find_by(user: current_user)
  end

  def set_gon
    gon.question_id = @question.id
    gon.current_user_id = current_user&.id
  end

  def publish_question
    return if @question.errors.any?

    ActionCable.server.broadcast(
      'questions',
      ApplicationController.render(
        partial: 'questions/question',
        locals: {
          question: @question,
          current_user: current_user
        }
      )
    )
  end

  def find_question
    @question = Question.with_attached_files.find(params[:id])
  end

  def question_params
    params.require(:question).permit(:title, :body, files: [], links_attributes: %i[id name url _destroy done],
                                                    reward_attributes: %i[id title image])
  end
end

app/helpers/questions_helper.rb
module QuestionsHelper
end

app/views/questions/_form.html.slim
= form_with(model:  @question, local: true) do |form|
  .card-body
    = render 'shared/errors', resource: @question
    div
      = form.label :title
      = form.text_field :title, class: 'form-control'
    div
      br
      = form.label :body
      = form.text_area :body, class: 'form-control'
    br
    div
      .reward
        ' Reward
        = form.fields_for :reward do |reward|
          = render 'rewards/form', r: reward
    br
    row
      = form.fields_for :links do |link|
        = render 'shared/link_fields', f: link
      .links
        = link_to_add_association 'add link', form, :links, partial: 'shared/link_fields', class: 'btn btn-sm btn-success btn-block'
    div.text-right
      = render partial: 'files/file', locals: { resources: @question, action_edit: true }
    div
      br
      = form.label :files
      = form.file_field :files, class: 'form-control-file', multiple: true
      -if form.object.files.attached?
        - form.object.files.each do |file|
          div { id="attachment_#{file.id}" }
            = form.hidden_field :files, value: file.signed_id, multiple: true
      br
      div
        = form.submit 'Update', class: "actions btn  btn-sm btn-success"

app/views/questions/_question.html.slim
div[id="question_#{question.id}"]
  .col-sm-12
    .card
      .card-body
        .row
          .col-1
            div.text-center.question-row.vote
              = render 'shared/vote', resource: question, current_user: current_user
          .col-11
            div
              h3= link_to question.title, question_path(question)
              p= question.body
        .row
          .col-1
            - if question.best_answer.blank?
              div.text-center#answer-count
                div
                  small.font-weight-bold= question.answers.count
                div
                  small= "answers"
            - else
              div.text-center#best-answer
                div
                  small.font-weight-bold= question.answers.count
                div
                  small= "answers"
          .col-11
            div[style="position: absolute; right: 15px" ]
              = render 'shared/create_at', resources: question
br

app/views/questions/edit.html.slim
.card
  .card-header
    h4
      ' Edit question
  = render 'questions/form'

app/views/questions/index.html.slim
.questions#questions
  = render @questions

- if can?(:create, Question)
  p= link_to 'Ask question', new_question_path

app/views/questions/new.html.slim
= render 'shared/errors', resource: @question

= form_with model: @question do |form|
  p
    = form.label :title
    = form.text_field :title, class: 'form-control'
  p
    = form.label :body
    = form.text_area :body, class: 'form-control'
  p
    = form.label :files
    = form.file_field :files, multiple: true

  .card
    .card-body
      div
      .reward
        | Reward:
        hr
        = form.fields_for :reward, @question.build_reward do |reward|
          = render 'rewards/form', r: reward
  br
  .card
    .card-body
      p Links:
      div
        = form.fields_for :links do |link|
          = render 'shared/link_fields', f: link
        .links
          = link_to_add_association 'add link', form, :links, partial: 'shared/link_fields', class: 'btn btn-sm btn-success btn-block'
  br
  p
    = form.submit 'Ask', class: 'btn btn-sm btn-primary btn-block'

app/views/questions/show.html.slim
h1= @question.title
p= @question.body

.subscription
  - if can?(:create, Subscription)
    = render 'subscriptions/subscription', resource: @question

div.text-right
  = render partial: 'files/file', locals: { resources: @question, action_edit: false }

- unless @question.links.blank?
  hr
  = render partial: 'shared/link', locals: { resources: @question }

- unless @question.reward.blank?
  hr
  ' Reward:
  p= @question.reward.title

- if can?(:update, @question)
  br
  div.text-right
    = link_to 'Edit question', edit_question_path(@question), class: 'btn btn-warning'

    - if can?(:destroy, @question)
      = link_to 'Delete question', question_path(@question), method: :delete, class: 'btn btn-danger'
-if can?(:create, Comment)
  hr
  = render 'comments/comments', resource: @question
br
- if current_user
  = render 'comments/form', resource: @question

hr
.answers
  = render 'answers/answers', best_answer: @best_answer, other_answers: @other_answers

.answer-errors
  =render 'shared/errors', resource: @answer

- if can?(:create, Answer)
  div= render 'answers/form'