config/routes.rb
require 'sidekiq/web'

Rails.application.routes.draw do
  authenticate :user, lambda { |u| u.admin? } do
    mount Sidekiq::Web => '/sidekiq'
  end

  use_doorkeeper
  devise_for :users, controllers: { omniauth_callbacks: 'oauth_callbacks' }
  root to: 'questions#index'

  get '/user/get_email', to: 'users#new'
  post '/user/set_email', to: 'users#create'

  namespace :api do
    namespace :v1 do
      resources :profiles, only: [:index] do
        get :me, on: :collection
      end

      resources :questions, except: %i[new edit] do
        resources :answers, except: %i[new edit], shallow: true
      end
    end
  end

  concern :voted do
    member do
      patch :vote_up
      patch :vote_down
      delete :vote_cancel
    end
  end

  concern :commentable do
    resources :comments, only: :create, shallow: true
  end

  resources :files, only: [:destroy]
  resources :questions, concerns: %i[voted commentable] do
    resources :answers, concerns: %i[voted commentable], shallow: true do
      patch :mark_as_best, on: :member
    end
    resources :subscriptions, only: %i[create destroy], shallow: true
  end

  resources :rewards, only: :index
  resources :searches, only: :index

  mount ActionCable.server => '/cable'
end

app/models/ability.rb
# frozen_string_literal: true

class Ability
  include CanCan::Ability

  attr_reader :user

  def initialize(user)
    @user = user

    if user
      user.admin? ? admin_ability : user_ability
    else
      guest_ability
    end
  end

  private

  def guest_ability
    can :read, :all
  end

  def admin_ability
    can :manage, :all
  end

  def user_ability
    guest_ability

    can :index, User
    can :me, User

    can :create, [Question, Answer, Comment, Subscription]

    can :update, [Question, Answer], user_id: user.id
    can :destroy, [Question, Answer, Subscription], user_id: user.id

    can :destroy, ActiveStorage::Attachment do |file|
      user.author_of?(file.record)
    end

    can :destroy, Link, linkable: { user_id: user.id }

    can :mark_as_best, Answer, question: { user_id: user.id }

    can %i[vote_up vote_down], [Answer, Question] do |votable|
      !user.author_of?(votable)
    end

    can :vote_cancel, [Answer, Question] do |votable|
      votable.votes.find_by(user: user).present?
    end
  end
end

app/models/answer.rb
class Answer < ApplicationRecord
  include Linkable
  include Votable
  include Commentable

  belongs_to :question
  belongs_to :user

  has_many_attached :files

  default_scope -> { order(created_at: :desc) }

  validates :body, presence: true

  after_create :email_notification

  private

  def email_notification
    NewAnswerNotificationJob.perform_later(self)
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true

  def type_id
    "#{self.class.name.downcase}_#{id}"
  end
end

app/models/authorization.rb
class Authorization < ApplicationRecord
  belongs_to :user

  validates :provider, presence: true
  validates :uid, presence: true, uniqueness: { scope: :provider }
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :user
  belongs_to :commentable, polymorphic: true

  validates :body, :user, presence: true
end

app/models/link.rb
class Link < ApplicationRecord
  belongs_to :linkable, polymorphic: true

  validates :name, :url, presence: true
  validates :url, format: { with: URI::DEFAULT_PARSER.make_regexp } # URI.regexp

  def gist?
    url.include?('gist.github.com')
  end
end

app/models/question.rb
class Question < ApplicationRecord
  include Linkable
  include Votable
  include Commentable

  has_many :answers, dependent: :destroy
  has_many :subscriptions, dependent: :destroy
  belongs_to :user
  belongs_to :best_answer, class_name: 'Answer', optional: true
  has_one :reward, dependent: :destroy

  has_many_attached :files

  accepts_nested_attributes_for :reward, reject_if: :all_blank

  default_scope -> { order(created_at: :desc) }

  validates :title, :body, presence: true

  after_create :subscribe_to_author!

  def mark_as_best(answer)
    transaction do
      update!(best_answer: answer)
      reward.update!(user: answer.user)
    end
  end

  def other_answers
    answers.where.not(id: best_answer)
  end

  private

  def subscribe_to_author!
    subscriptions.create!(user: user)
  end
end

app/models/reward.rb
class Reward < ApplicationRecord
  belongs_to :question
  belongs_to :user, optional: true

  validates :title, :image, presence: true

  has_one_attached :image
end

app/models/subscription.rb
class Subscription < ApplicationRecord
  belongs_to :user
  belongs_to :question
end

app/models/user.rb
class User < ApplicationRecord
  has_many :questions, dependent: :destroy
  has_many :answers, dependent: :destroy
  has_many :rewards, dependent: :destroy
  has_many :votes, dependent: :destroy
  has_many :authorizations, dependent: :destroy
  has_many :subscriptions, dependent: :destroy

  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable,
         :registerable,
         :recoverable,
         :rememberable,
         :validatable,
         # :confirmable,
         :omniauthable, omniauth_providers: %i[github vkontakte]

  def author_of?(object)
    id == object.user_id
  end

  def subscribed_of?(object)
    object.subscriptions.where(user: self).exists?
  end
end

app/models/vote.rb
class Vote < ApplicationRecord
  belongs_to :user
  belongs_to :votable, polymorphic: true

  validates :value, presence: true
  validates :user, presence: true, uniqueness: { scope: %i[votable_id votable_type] }
end

app/controllers/files_controller.rb
class FilesController < ApplicationController
  def destroy
    @file = ActiveStorage::Attachment.find(params[:id])
    @file.purge if current_user.author_of?(@file.record)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  skip_authorization_check

  def new; end

  def create
    password = Devise.friendly_token[0, 20]

    if User.find_by(email: params['email'])
      redirect_to root_path, alert: 'Email has already been taken!'
    else
      begin
        user = User.create!(email: email_params[:email], password: password, password_confirmation: password)
        user.authorizations.create(provider: session[:auth]['provider'], uid: session[:auth]['uid'])
        redirect_to root_path, alert: 'Account create! Please confirm your Email!'
      rescue StandardError => e
        redirect_to root_path, alert: e.message.to_s
      end
    end
  end

  private

  def email_params
    params.permit(:email)
  end
end

app/helpers/answers_helper.rb
module AnswersHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
  def current_year
    Time.now.year
  end

  def github_url(author, repo)
    link_to 'ibekirov', "https://github.com/#{author}/#{repo}", target: '_blank', class: 'text-white'
  end
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/questions_helper.rb
module QuestionsHelper
end

app/helpers/rewards_helper.rb
module RewardsHelper
end

app/helpers/searches_helper.rb
module SearchesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>StackOverFlow</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= action_cable_meta_tag %>
    <%= Gon::Base.render_data %>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/css/bootstrap.min.css" integrity="sha384-TX8t27EcRE3e/ihU7zmQxVncDAy5uIKz4rEkgIXeMed4M0jlfIDPvg6uqKI2xXr2" crossorigin="anonymous">
    <link rel="stylesheet" href="https://pro.fontawesome.com/releases/v5.10.0/css/all.css" integrity="sha384-AYmEC3Yw5cVb3ZcuHtOA93w35dYTsvhLPVnYs9eStHfGJvOvKxVfELGroGkvsg+p" crossorigin="anonymous"/>
  </head>

  <body>
    <%= render 'shared/user_navbar' %>

    <div class="content">
      <div class="container">
        <p class="notice"><%= notice %></p>
        <p class="alert"><%= alert %></p>
        <%= yield %>
      </div>
    </div>

    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ho+j7jyWK8fNQe+A12Hb8AhRq26LrZ/JpcUGGOn+Y7RsweNrtN/tE3MoK7ZeZDyx" crossorigin="anonymous"></script>
  </body>

  <br>
  <br>
  <%= render 'shared/footer', style: 'info' %>
</html>

app/views/shared/_create_at.html.slim
div.text-right
  small.font-italic= "created by: #{resources.user.email}"
  div.text-right
    small.font-italic= resources.created_at.strftime("%d.%m.%Y %H:%M:%S")

app/views/shared/_errors.html.slim
-if resource&.errors.present?
  b= "#{resource.errors.count} error(s) detected: "
  ul
    -resource.errors.full_messages.each do |message|
      li= message

app/views/shared/_footer.html.erb
<footer class="footer bg-<%= style %> text-white text-center text-lg-start">
  <div class="container p-4">
    <div class="row">
      <div class="col-lg-9 col-md-12 mb-4 mb-md-0">
        <h5 class="text-uppercase">Информация</h5>

        <p>
          Данный учебный проект разрабатывался на базе прохождения курса "Продвинутый Ruby on Rails".
          <br>
          Представлен онлайн-школой:
          <%= link_to 'Thinknetica', 'https://thinknetica.com/', target: '_blank', class: "text-white" %><br>
          Разработан для создания вопросов и получение на них ответов
        </p>
      </div>

      <div class="col-lg-3 col-md-6 mb-4 mb-md-0">
        <h5 class="text-uppercase">Ссылки</h5>

        <ul class="list-unstyled mb-0">
          <li>
          </li>
        </ul>
      </div>

    </div>
  </div>
  <div class="text-center p-3" style="background-color: rgba(0, 0, 0, 0.2)">
    © <%= current_year %> Copyright:
    <%= github_url('IljaBekirov', 'qna') %>
  </div>
</footer>

app/views/shared/_link.html.slim
.links
  p Links
  ul
    - resources.links.each do |link|
      li= link_to link.name, link.url
      - if link.gist?
        = javascript_include_tag link.url+".js"

app/views/shared/_link_fields.html.slim
.nested-fields
  .card
    .card-body
      .field
        = f.label :name, 'Link name'
        br
        = f.text_field :name, class: 'form-control'
      .field
        = f.label :url
        = f.text_field :url, class: 'form-control'
      br
      = link_to_remove_association "remove link", f, class: 'btn btn-sm btn-danger btn-block'
br

app/views/shared/_user_navbar.html.slim
nav.navbar.navbar-expand-lg.navbar-light.bg-info
  a.navbar-brand href="#" StackOverFlow
  #navbarSupportedContent.collapse.navbar-collapse
    ul.navbar-nav.mr-auto
      li.nav-item
        = link_to 'Questions', questions_path, class: 'nav-link'
      - if current_user
        li.nav-item
          = link_to "Rewards", rewards_path, class: 'nav-link'
    div{ style="padding-right: 10px;" }
      = render 'searches/search_form'
    .form-inline.my-2.my-lg-0
      - if user_signed_in?
        .navbar-text
          = current_user.email
        = link_to 'Sign out', destroy_user_session_path, method: :delete, class: 'btn btn-outline-secondary ml-2 mr-2'
      - else
        = link_to 'Sign in', new_user_session_path, class: 'btn btn-info ml-2 mr-2'
        = link_to 'Sign up', new_user_registration_path, class: 'btn btn-info ml-2 mr-2'

app/views/shared/_vote.html.slim
.small
  ' vote
-if current_user && !current_user.author_of?(resource)
  .vote.vote-up
    = link_to polymorphic_path(resource, action: :vote_up), method: :patch, data: { type: :json }, remote: true
      i.fas.fa-caret-up
.vote
  .rating
    = resource.rating

-if current_user && !current_user.author_of?(resource)
  .vote.vote-down
    = link_to polymorphic_path(resource, action: :vote_down), method: :patch, data: { type: :json }, remote: true
      i.fas.fa-caret-down
    .vote-cancel.small
      = link_to 'cancel', polymorphic_path(resource, action: :vote_cancel),
              method: :delete,
              data: { type: :json },
              remote: true