config/routes.rb
require 'sidekiq/web'

Rails.application.routes.draw do
  authenticate :user, lambda { |u| u.admin? } do
    mount Sidekiq::Web => '/sidekiq'
  end

  use_doorkeeper
  devise_for :users, controllers: { omniauth_callbacks: 'oauth_callbacks' }
  root to: 'questions#index'

  get '/user/get_email', to: 'users#new'
  post '/user/set_email', to: 'users#create'

  namespace :api do
    namespace :v1 do
      resources :profiles, only: [:index] do
        get :me, on: :collection
      end

      resources :questions, except: %i[new edit] do
        resources :answers, except: %i[new edit], shallow: true
      end
    end
  end

  concern :voted do
    member do
      patch :vote_up
      patch :vote_down
      delete :vote_cancel
    end
  end

  concern :commentable do
    resources :comments, only: :create, shallow: true
  end

  resources :files, only: [:destroy]
  resources :questions, concerns: %i[voted commentable] do
    resources :answers, concerns: %i[voted commentable], shallow: true do
      patch :mark_as_best, on: :member
    end
    resources :subscriptions, only: %i[create destroy], shallow: true
  end

  resources :rewards, only: :index
  resources :searches, only: :index

  mount ActionCable.server => '/cable'
end

app/models/answer.rb
class Answer < ApplicationRecord
  include Linkable
  include Votable
  include Commentable

  belongs_to :question
  belongs_to :user

  has_many_attached :files

  default_scope -> { order(created_at: :desc) }

  validates :body, presence: true

  after_create :email_notification

  private

  def email_notification
    NewAnswerNotificationJob.perform_later(self)
  end
end

app/controllers/answers_controller.rb
class AnswersController < ApplicationController
  include Voted

  before_action :authenticate_user!, only: %i[create destroy update edit mark_as_best]
  before_action :find_question, only: [:create]
  before_action :find_answer, only: %i[show destroy update mark_as_best edit]
  before_action :load_answers, only: %i[create update]
  after_action :publish_answer, only: :create

  authorize_resource

  def show; end

  def new; end

  def edit; end

  def create
    @answer = @question.answers.new(answer_params)
    @answer.user = current_user
    respond_to do |format|
      if @answer.save
        format.js { flash[:notice] = 'Your answer successfully created.' }
      else
        format.js { flash[:alert] = 'Your have an errors!' }
      end
    end
  end

  def update
    if current_user.author_of?(@answer)
      respond_to do |format|
        if @answer.update(answer_params)
          format.js { flash[:notice] = 'Your answer is updated' }
        else
          format.js { flash[:error] = 'Answer is not updated' }
        end
      end
    else
      flash[:error] = 'You are not author of this answer'
      render 'questions/show'
    end
  end

  def destroy
    @answer.destroy if current_user.author_of?(@answer)
  end

  def mark_as_best
    @question = @answer.question
    @question.mark_as_best(@answer) if current_user.author_of?(@question)
    load_answers
  end

  private

  def publish_answer
    return if @answer.errors.any?

    ActionCable.server.broadcast("question_#{@answer.question_id}",
                                 answer: @answer,
                                 email: @answer.user.email,
                                 created_at: @answer.created_at.strftime("%d.%m.%Y %H:%M:%S"),
                                 links: @answer.links)
  end

  def load_answers
    @question ||= @answer.question
    @best_answer ||= @question.best_answer
    @other_answers ||= @question.other_answers
  end

  def find_question
    @question = Question.find(params[:question_id])
  end

  def find_answer
    @answer = Answer.with_attached_files.find(params[:id])
  end

  def answer_params
    params.require(:answer).permit(:body, files: [], links_attributes: %i[id name url _destroy done])
  end
end

app/controllers/api/v1/answers_controller.rb
class Api::V1::AnswersController < Api::V1::BaseController
  skip_authorization_check

  before_action :find_question, only: %i[index create]
  before_action :find_answer, only: %i[show update destroy]

  def index
    render json: @question.answers
  end

  def show
    render json: @answer, serializer: AnswerSeparateSerializer
  end

  def create
    @answer = @question.answers.new(answer_params)
    @answer.user = current_resource_owner

    if @answer.save
      render json: @answer, status: :created
    else
      render json: { errors: @answer.errors }, status: :unprocessable_entity
    end
  end

  def update
    authorize! :update, @answer

    if @answer.update(answer_params)
      render json: @answer, status: :created
    else
      render json: { errors: @answer.errors }, status: :unprocessable_entity
    end
  end

  def destroy
    authorize! :destroy, @answer

    @answer.destroy
    render json: { messages: ['Answer was successfully deleted.'] }
  end

  private

  def answer_params
    params.require(:answer).permit(:body)
  end

  def find_question
    @question = Question.find(params[:question_id])
  end

  def find_answer
    @answer = Answer.find(params[:id])
  end
end

app/helpers/answers_helper.rb
module AnswersHelper
end

app/views/answers/_answers.html.slim
- if best_answer.present?
  = content_tag :div, id: "answer_#{best_answer.id}", class: 'mt-3'
    .row
      .col-sm-12
        .best_answer
          = render 'answers/body_answers', resources: best_answer
- if other_answers.present?
  - other_answers.map do |answer|
    = content_tag :div, id: "answer_#{answer.id}", class: 'mt-3'
      .row
        .col-sm-12
          .card
            = render 'answers/body_answers', resources: answer

app/views/answers/_body_answers.html.slim
.card-body
  = content_tag :p, resources.body, class: "card-text"
  - unless resources.links.blank?
    br
    div
      = render partial: 'shared/link', locals: { resources: resources }
  div
    = render 'shared/vote', resource: resources
  div.text-right
    = render partial: 'files/file', locals: { resources: resources, action_edit: false }

  - if current_user
    .row
      .col-2
      .col-10
        hr
        = render 'comments/comments', resource: resources
        .mt-1.text-right
          -if can?(:create, Comment)
            = render 'comments/form', resource: resources
    hr
    br
    = render 'shared/create_at', resources: resources
      br
    div.text-right
      br
      - if current_user&.author_of?(@question) && @question.best_answer != resources
        = link_to mark_as_best_answer_path(resources), class: "btn btn-outline-success btn-sm", id: "best_#{resources.id}", method: :patch, remote: true do
          i.fas.fa-thumbs-up
      - if can?(:update, resources)
        = link_to '#', class: 'btn btn-outline-warning btn-sm edit-answer-link', data: { answer_id: resources.id } do
          i.fas.fa-edit
          '  Edit
        = link_to answer_path(resources), method: :delete, class: 'btn btn-outline-danger btn-sm', remote: true do
          i.far.fa-trash-alt
          '  Delete
    = form_with model: resources, class: 'hidden', html: { id: "edit-answer-#{resources.id}" }, local: false do |form|
      = form.label :body, 'Your answer'
      = form.text_area :body, class: 'form-control'
      div.text-right
        = render partial: 'files/file', locals: { resources: resources, action_edit: true }
      br
      row
        = form.fields_for :links do |link|
          = render 'shared/link_fields', f: link
        .links
          = link_to_add_association 'add link', form, :links, partial: 'shared/link_fields', class: 'btn btn-sm btn-success btn-block'

      div
        br
        = form.label :files
        = form.file_field :files, class: 'form-control-file', multiple: true
        - if form.object.files.attached?
          - form.object.files.each do |file|
            div { id="attachment_#{file.id}" }
              = form.hidden_field :files, value: file.signed_id, multiple: true
      br
      = form.submit 'Save', class: 'btn btn-outline-success'

app/views/answers/_form.html.slim
hr
h5= 'Answer a question'

= form_with(model: [@question, @answer], class: 'new-answer', local: false) do |form|
  = render 'shared/errors', resource: @answer
  p
    = form.label :body
    = form.text_area :body, class: 'form-control'
  hr
  .card
    .card-body
      p Links:
      div
        = form.fields_for :links do |link|
          = render 'shared/link_fields', f: link
        .links
          = link_to_add_association 'add link', form, :links, partial: 'shared/link_fields', class: 'btn btn-sm btn-success btn-block'
  hr
  p
    = form.label :files
    br
    = form.file_field :files, multiple: true
  p
    = form.submit 'Answer', class: 'btn btn-sm btn-primary btn-block'

app/views/answers/_form_answers.html.slim
.card-body
  = content_tag :p, resources.body, class: "card-text"
  br
  - if current_user
    div.text-right
      - if current_user&.author_of?(@question)
        = link_to mark_as_best_answer_path(resources), class: "btn btn-outline-success", id: "best_#{resources.id}", method: :patch, remote: true do
          i.fas.fa-thumbs-up
      - if current_user.author_of?(resources)
        = link_to '#', class: 'btn btn-outline-warning edit-answer-link', data: { answer_id: resources.id } do
          i.fas.fa-edit
          '  Edit
        = link_to answer_path(resources), method: :delete, class: 'btn btn-outline-danger', remote: true do
          i.far.fa-trash-alt
          '  Delete
    = form_with model: resources, class: 'hidden', html: { id: "edit-answer-#{resources.id}" }, local: false do |f|
      = f.label :body, 'Your answer'
      = f.text_area :body, class: 'form-control'
      = f.submit 'Save', class: 'btn btn-outline-success'

app/views/answers/create.js.erb
$('.alert').html("<%= flash['alert'] %>")
$('.notice').html("<%= flash['notice'] %>")
$('.answer-errors').html("<%= render 'shared/errors', resource: @answer %>");

<% if @answer.persisted? %>
  $('.answers').html('<%= j render 'answers/answers', best_answer: @best_answer, other_answers: @other_answers %>');
  $('.new-answer #answer_body').val('');
<% end %>

app/views/answers/destroy.js.erb
document.getElementById('<%= dom_id(@answer) %>').remove();

app/views/answers/mark_as_best.js.erb
$('.answers').html('<%= j render 'answers/answers', best_answer: @best_answer, other_answers: @other_answers %>');

app/views/answers/new.html.slim
div= render 'form'

app/views/answers/update.js.erb
$('.alert').html("<%= flash['alert'] %>")
$('.notice').html("<%= flash['notice'] %>")
$('.answer-errors').html("<%= render 'shared/errors', resource: @answer %>");

<% unless @answer.errors.present? %>
$('.answers').html('<%= j render 'answers/answers', best_answer: @best_answer, other_answers: @other_answers %>');
<% end %>